### ISSUE TITLE
SpeckleCore throws error in Sandbox

### ISSUE THREAD

**Issue by mishaelnuh** [speckleworks/SpeckleDynamo#63]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

#### Expected Behaviour
SpeckleCore should be able to use serialize and serialize JSON,

#### Actual Behaviour
Dynamo sandbox loads Newtonsoft.Json version 8.0.0.0 which does not have the NamingStrategy property for DefaultContractResolver, causing an error.

Problematic line:
[`ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver() { NamingStrategy = new Newtonsoft.Json.Serialization.CamelCaseNamingStrategy() }`](https://github.com/speckleworks/SpeckleCore/blob/master/SpeckleCore/ApiClient/SpeckleApiClientExtension.cs#L85-L88)

![image](https://user-images.githubusercontent.com/45694155/55517002-06e25200-563d-11e9-8a6d-c23b64610798.png)

#### Affected Projects
SpeckleDynamo

**Comment by teocomi** [comment]
Thanks Mish, we’re aware of this and have a fix in mind! Will try implement next week.

For the time being Dynamo Revit should be loading the correct version.

**Comment by teocomi** [comment]
This should be fixed in: https://github.com/speckleworks/SpeckleDynamo/commit/dad4e2889661b52f97b44cead3799343631d716c

We opted for manually adding and renaming Newtonsoft to the SpeckleCore repo and referencing it with an alias, then we can have both v8 and v12 :)

Will merge to master sometime this week!
