### ISSUE TITLE
Polyline conversion is inconsistent

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleDynamo#73]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
Speckle polylines convert the same way every time

#### Actual Behaviour
Some PL become rectangles, some become polygons, some become polycurves, some remain SpecklePolyline

#### Affected Projects
SpeckleCoreGeometry

#### Proposed Solution (if any)
Update conversion logic

**Comment by teocomi** [comment]
@alvpickmans any chance you wanna have a look at this?

**Comment by mswaidan** [comment]
Was planning on taking a crack at it today, but if someone who’s more
familiar with this project wants to handle it...

**Comment by alvpickmans** [comment]
From memory speckle only had SpecklePolyline to convert a group of curves,
so to keep the original geometry from Dynamo (rectangle, polygon,etc) it
has some checks to convert from a generic SP to the closest likely
geometry. Otherwise you would send a rectangle and receive back a polycurve
the least.

I think that's the most desirable way as it only affects when dealing with
a stream in Dynamo, but happy to discuss any side effects.

I'm on holidays atm camping somewhere in France, so feel free to take over
it if urgent :)

**Comment by mswaidan** [comment]
That makes sense if you're only sending Dynamo -> Dynamo, but I think it's leading to unpredictable results in other cases: e.g. if I sent a polyline from Rhino or GH, I expect to get a polyline out on the other side.

I can think of two ways to solve both these cases:

1. Easy / less impact on SpeckleCoreGeometry: move the logic you're using to cast from SpecklePolyline -> rectangle or polygon _after_ conversion, as a part of the Dynamo graph

**Comment by mswaidan** [comment]
If option 1 is okay, https://github.com/speckleworks/SpeckleCoreGeometry/pull/12

**Comment by alvpickmans** [comment]
Sure thing, although I'm not using speckle on any workflow that much to
consider that a big issue as polygons, rectangles and polycurve all inherit
from curves. Having them casted to their corresponding types brings a
bigger range of tools and properties to be used, but not sure if Dynamo has
to be dependent on Rhino/GH or not.

As far as I recall, a polygon in dynamo can use all the same tools from a
polycurve but not vice versa.
